import os

# Define the structure (matches the categories we used to generate them)
categories = {
    "🌱 Staple Crops & Gravity": [
        "The Potato Paradox", "Hypobaric Quinoa", "Duckweed Radiation Shields", "Sweet Potato",
        "Oil Pressing in Microgravity", "Wheat Dwarfism", "Aeroponic Rice", "Peanut Allergens",
        "Structural Bamboo", "Moringa"
    ],
    "🦗 Alternative Protein": [
        "The Caloric ROI of Entomophagy", "Mealworms and Styrofoam", "Black Soldier Fly", 
        "Microgravity Aquaponics", "Shrimp Shell Formation", "Myco-Shielding", "Yeast Vats", 
        "Cellular Agriculture", "Silkworm Textiles", "Escargot Snails", "Bacterial Cellulose", 
        "Waste-to-Biomass"
    ],
    "💧 Water & Waste Loops": [
        "Closed-Loop Hydrology", "Greywater Surfactants", "Urine Electrolysis", 
        "Transpiration Capture", "Aeroponic Clogging", "Fogponics", "Biochar Pyrolysis", 
        "Methane Digesters", "Fecal Compaction", "Sweat Salt Recovery", "Pharma-Filtration"
    ],
    "🧱 Regolith & ISRU": [
        "Regolith Remediation", "Hydroponic Substrates", "Simulant MGS-1", "Clay Swelling", 
        "Zeolite Synthesis", "Microwave Sintering", "Magnetic Separation", "Sulfate Reduction", 
        "Perchlorate Byproducts", "Synthetic Soil Crusts", "Geophagous Worms", "Nitrogen Fixation"
    ],
    "💡 Lighting & Power": [
        "Algae Photobioreactors", "Monochromatic Defects", "Martian Sol Adaptation", 
        "Far-Red Triggers", "UV-B Upregulation", "Fiber Optic Collection", "Thermal Rejection", 
        "Inter-Canopy LEDs", "Pulsed Light", "Gamma Radiation Shielding", "Solar Storm Protocol"
    ],
    "💨 Atmosphere & Gas": [
        "Ethylene Scrubbing", "CO2 Toxicity", "High-O2 Fire Risks", "Terpene Accumulation", 
        "Vapor Pressure Deficit", "Hypobaric Physiology", "Dust Filtration", "Off-Gassing", 
        "Thigmomorphogenesis", "Argon Buffering", "Biosphere 2 Revisited"
    ],
    "🤖 Robotics & Automation": [
        "Automated Pollination", "Seedling Robots", "Soft Robotics", "Root Tomography", 
        "Ion-Selective Electrodes", "IR Stress Detection", "Micro-Drone Mixing", 
        "3D Printed Tools", "Hyperspectral Imaging", "Fail-Safe Logic", "Telemetry Compression"
    ],
    "💊 In-Situ Pharmacy": [
        "Genetic Resilience", "Analgesic Poppies", "Aloe Vera", "Willow Bark", "Stevia", 
        "Enzymatic Caffeine", "Molecular Farming", "Space Brewing", "Olfactory Stimulation", 
        "Dandelion Latex", "Industrial Hemp"
    ],
    "🚀 Extreme Environments (The Frontier)": [
        "Lava Tube Farming", "Ice Cap Agriculture", "Dust Storm Resilience", 
        "Micrometeorite Punctures", "Planetary Protection", "Seed Vaults", 
        "Grafting Techniques", "Polyculture Guilds", "Nematodes", "The Salad Machine",
        "Psychological Botany"
    ]
}

# Generate the Markdown content
content = """# 🏛 Pillar 1: Exoplanetary Agriculture
### Engineering Life Support for Hostile Environments

This archive contains **100 technical research notes** focusing on the transition from 'Outpost Survival' to 'Colony Sustainability.'

---

"""

for category, titles in categories.items():
    content += f"## {category}\n"
    for title in titles:
        # Construct relative link
        filename = title.replace(" ", "_").replace("-", "_") + ".md"
        # Check if file exists to avoid broken links (optional, but good practice)
        link = f"- [{title}]({filename})\n"
        content += link
    content += "\n"

content += "---\n*Generated by The Global Pulse Observatory Engine*"

# Write the file
output_path = "research_articles/1_Exoplanetary_Agriculture/index.md"
with open(output_path, "w") as f:
    f.write(content)

print(f"✅ Created Landing Page at: {output_path}")
